---
version: "2"
services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: rpi-nextcloud
    hostname: rpi-nextcloud
    environment:
      - PUID=1000   # use 'whoami' and 'id your_user_name_from_whoami' 
      - PGID=1000   # same as above
      - TZ=Europe/Berlin  # change to your timezone
    volumes:
      - /home/bk/docker-data/rpi-ncp/config:/config  # change path before ':'
      - /home/bk/docker-data/rpi-ncp/data:/data     # change path before ':'
    #ports:
      #- 8443:443
    restart: unless-stopped
    depends_on:
      - nextcloud_db
  nextcloud_db:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: rpi-nextcloud-db
    hostname: rpi-nextcloud-db
    environment:
      - PUID=1000 # see PUID and PGID above
      - PGID=1000 # same as above
      - MYSQL_ROOT_PASSWORD=rootpass # change it
      - TZ=Europe/Berlin  # chnge to your timezone
      - MYSQL_DATABASE=ncpdb # change it
      - MYSQL_USER=ncpuser # change it
      - MYSQL_PASSWORD=mysqlpass # change it
    volumes:
      - /home/bk/docker-data/rpi-ncp/db:/config  # change path before ':'
    restart: unless-stopped
networks:
  default:
    name: vpn-network
    external: true
