version: '3.4'

services:
  samba:
    image: dperson/samba
    container_name: rpi-samba
    hostname: rpi-samba
    command: -u "bk-user;pass" -s "/bk-shared;/share;yes;no;yes;bk-user" # chnage user name (bk-user), password (pass) and /home/bk path to directory you want to share with samba 
    volumes:
      - /home/bk:/share # chnage /home/bk path to directory you want to share with samba (same as in 'command') 
    environment:
      - TZ=Europe/Berlin # chnge to your timezone
      - WORKGROUP=rpi
      - USERID=1000 # use 'whoami' and 'id your_user_name_from_whoami' 
      - GROUPID=1000 # same as above
    #ports:
      #- 139:139
      #- 445:445
    restart: unless-stopped
networks:
  default:
    name: vpn-network
    external: true
